### ISSUE TITLE
use quartodoc for docs?

### ISSUE THREAD

**Issue by JoFrhwld** [Forced-Alignment-and-Vowel-Extraction/fave-recode#8]
https://machow.github.io/quartodoc/

**Comment by chrisbrickhouse** [comment]
I think migrating is a good idea especially since it will help with integration into ling-methods-hub and existing knowledge of markdown. As well known as sphinx is, there are too many pain points for users, developers, and tutorial writers.

I'm not sure how resource intensive this migration will be, but I can take this on next quarter around late February, early March if that's not too long a time lag.

**Comment by JoFrhwld** [comment]
Well, right now there's hardly any pain to migrating since there's hardly any docs for this package yet! When I glanced it over, I think the trickiest parts will be:

1. Getting the right github actions configured.
2. Deploying to ReadTheDocs correctly.

My one hesitation might be the stability & future of `quartodocs`, which is *not* being developed by the core quarto team. On the other hand, quarto itself seems to have a lot of institutional and community energy, so hopefully any future migration to a different docs renderer would involve just swapping out a config file as long as we've already got the source qmd files in place.

**Comment by JoFrhwld** [comment]
I think a broader discussion to be had is where we publish all the docs. Right now I think having each individual python package on RTD aligns with user expectations. But once more pieces are in place, publishing the under the fave organization github would be more cohesive.

**Comment by JoFrhwld** [comment]
I've *largely* got this working. I should pull out the basics, maybe for the .github repo
